[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "a69dacac96a1c184ce282d9e5915f9776355b02f"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.7"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "IterativeEigensolvers", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "SparseArrays", "SuiteSparse", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "800678d45b6614bc0b57fca5199e4abe394fd318"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.63.0"

[[Conda]]
deps = ["BinDeps", "Compat", "JSON", "Libdl"]
git-tree-sha1 = "590e8f85aa24d966163aa390c415fe6730316f55"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "0.7.1"

[[Cxx]]
deps = ["Compat", "Test"]
git-tree-sha1 = "431f91a90928055c515f8b257fb9a6487ae31632"
repo-rev = "kf/xlawip"
repo-url = "https://github.com/jekbradbury/Cxx.jl"
uuid = "a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2"
version = "0.2.0+"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IterativeEigensolvers]]
uuid = "de555fa4-b82f-55e7-8b71-53f60bbc027d"

[[JSON]]
deps = ["Compat", "Nullables", "Sockets", "Unicode"]
git-tree-sha1 = "e2f6776e8bfd310b2ade13fba1faf99d8967d58f"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.17.2"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MacroTools]]
deps = ["Compat"]
path = "/Users/james.bradbury/.julia/dev/MacroTools"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.0+"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Nullables]]
deps = ["Compat"]
git-tree-sha1 = "23258f849603ad4fed3ce7dbcb8c0658920fa5ef"
uuid = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
version = "0.0.5"

[[Pkg]]
uuid = "fe1c5a76-5840-53d2-82f9-288dd83ce2ce"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[PyCall]]
deps = ["Compat", "Conda", "MacroTools", "VersionParsing"]
path = "/Users/james.bradbury/.julia/dev/PyCall"
uuid = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
version = "1.15.0+"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SuiteSparse]]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[URIParser]]
deps = ["Compat", "Unicode"]
git-tree-sha1 = "0f9c5e2d14e03fbd00696f9394e288bdd5adacbc"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.3.1"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "7afe8f83cd3f71519f44381a1f5d1845ea7ed1c5"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.0"
